### PR TITLE
License

### PR DESCRIPTION
**Pull request by jasonkarns**
Having the LICENSE file at root and named per convention allows tools to determine the project license easier/reliably.

Duplicating this info in the readme is unnecessary and potential for drift.

### CODE REVIEW

**Comment by ztombol** [comment]
I don't think there will be any drift regarding the licence. It's CC0 once, it's CC0 forever. But I'm okay with removing that section and I agree with renaming the licence file too.

Sometime soon, I want to write a contribution guidelines section in `bats-docs` that will explain that by contributing one automatically waives his/her copyrights and license their work under CC0. I'm planning to add a small licence shield/badge at the top of the README too. Probably after I hook up Travis.

Could you rename the licence file in one commit, i.e. `git mv`?

Thanks!

**_Update:**_ _Added request to do `git mv` -- 2016-02-10 19:42 UTC_

**Comment by jasonkarns** [comment]
squashed those commits and did a move. But the LICENSE file I used is github's built-in. 

There are neglible differences: 
image

image

**Comment by jasonkarns** [comment]
The disclaimer that was previously included is a disclaimer from CC to the person using the license. It's not part of the license itself. (And github includes a handy link back to the CC .org)

**Comment by ztombol** [comment]
Looks good. Merging. Thanks for the details too!

**Comment by jasonkarns** [comment]
cool. i'll open similar ones to the other repos

**Comment by ztombol** [comment]
That would be great! Thanks! :smile:

**Pull request merged**
